# Puerto del servidor (por si 8080 está ocupado)
server.port=8081

# Configuración de base de datos H2 en memoria [cite: 29, 31]
spring.datasource.url=jdbc:h2:mem:hardware_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Permite ver la consola de H2 en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console